# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm ci
            - run: npm run build --if-present
            # - run: npm test
            - name: Push to github pages
              # You may pin to the exact commit or the version.
              # uses: cpina/github-action-push-to-another-repository@07c4d7b3def0a8ebe788a8f2c843a4e1de4f6900
              uses: cpina/github-action-push-to-another-repository@v1.7.2
              with:
                  # Source before directory from the origin directory
                  # source-before-directory: # optional
                  # Source directory from the origin directory
                  source-directory: codelinez
                  # Name of the destination username/organization
                  destination-github-username: HDNRAY
                  # Destination repository
                  destination-repository-name: HDNRAY.github.io
                  # Email for the git commit
                  user-email: 110681032@qq.com
                  # Github server
                  # github-server: # optional, default is github.com
                  # [Optional] Name for the git commit. Defaults to the destination username/organization name
                  # user-name: # optional, default is
                  # [Optional] Username/organization for the destination repository
                  # destination-repository-username: # optional, default is
                  # [Optional] set target branch name for the destination repository. Defaults to "main"
                  # target-branch: # optional, default is main
                  # [Optional] commit message for the output repository. ORIGIN_COMMIT is replaced by the URL@commit in the origin repo
                  commit-message: Update from codeLinez
                  # [Optional] The directory to wipe and replace in the target repository
                  target-directory: codelinez
                  # [Optional] create target branch if not exist. Defaults to `false`
                  # create-target-branch-if-needed: # optional
